# Generated by Django 5.0 on 2026-07-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_pesapal_tracking_id'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mpesa', 'M-Pesa'), ('pesapal', 'Pesapal'), ('pay_on_delivery', 'Pay on Delivery')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='checkout.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'gateway'], name='payment_pay_order_i_fefd0a_idx'), models.Index(fields=['transaction_id'], name='payment_pay_transac_214c98_idx'), models.Index(fields=['status'], name='payment_pay_status_718335_idx')],
            },
        ),
    ]
