# Generated by Django 5.2.15 on 2026-07-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
