# Generated by Django 5.2.16 on 2026-07-15 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_pesapal_tracking_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_collected_at',
            field=models.DateTimeField(blank=True, help_text='When payment was collected on delivery', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cod_collected_by',
            field=models.ForeignKey(blank=True, help_text='Admin who marked payment as collected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special instructions for delivery team'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partial Payment'), ('collected', 'Payment Collected on Delivery'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
