# Generated by Django 5.0 on 2026-07-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_cod_collected_at_order_cod_collected_by_and_more'),
        ('shop', '0005_coupon_usedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code_used',
            field=models.CharField(blank=True, help_text='The coupon code that was applied', max_length=9),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied from coupon', max_digits=10),
        ),
    ]
