# Generated by Django 5.0 on 2026-07-28 18:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_cod_collected_at_order_cod_collected_by_and_more'),
        ('shop', '0004_productreview_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='9-character alphanumeric code (e.g., ABC123XYZ)', max_length=9, unique=True)),
                ('discount_percent', models.PositiveIntegerField(default=10, help_text='Discount percentage (e.g., 10 for 10%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('minimum_order', models.DecimalField(decimal_places=2, default=1000.0, help_text='Minimum order amount to apply this coupon', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (leave blank for no limit)', max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum number of times this coupon can be used (0 = unlimited)')),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(help_text='Coupon expiry date')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, help_text='Internal description for admin reference', max_length=255)),
                ('user', models.ForeignKey(blank=True, help_text='If set, only this user can use this coupon', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons', to='shop.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons', to='checkout.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('coupon', 'order')},
            },
        ),
    ]
